#cloud-config
##############################################
# web.yaml.tpl (offline + password login)
# - 오프라인: 패키지 설치 시도 없음
# - 입력: __HOSTNAME__, __HASHED_PASSWORD__ (SHA-512)  *아래 설명 참고
##############################################

preserve_hostname: false
manage_etc_hosts: true
hostname: "__HOSTNAME__"

# 기본 사용자: Ubuntu 이미지는 대개 'ubuntu'
# (RHEL/Alma/Rocky 계열은 'cloud-user'인 경우가 많으니 name만 바꿔 쓰세요)
users:
  - name: ubuntu
    lock_passwd: false
    # SHA-512 해시 사용 권장. 예) openssl passwd -6 'PlainPassword'
    # 결과 형태: $6$.... 로 시작
    passwd: "__HASHED_PASSWORD__"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

# SSH 비번 로그인 허용
ssh_pwauth: true

# 최초 로그인 시 비번 변경 강제(선택)
chpasswd:
  expire: true

# 패키지 작업 비활성(오프라인 안전)
package_update: false
package_upgrade: false
packages: []

# 테스트 페이지(임시 위치에 작성 후 runcmd에서 문서 루트로 복사)
write_files:
  - path: /opt/vmcatalog/web-index.html
    permissions: '0644'
    owner: root:root
    content: |
      <!doctype html>
      <html>
      <head><meta charset="utf-8"><title>__HOSTNAME__</title></head>
      <body>
        <h1>Hello from __HOSTNAME__ (offline)</h1>
        <p>This page was deployed by cloud-init.</p>
      </body>
      </html>

runcmd:
  - |
    #!/bin/bash
    set -euo pipefail

    # 1) sshd에 PasswordAuthentication yes 강제
    if grep -qE '^[#\s]*PasswordAuthentication' /etc/ssh/sshd_config; then
      sed -i 's/^[#\s]*PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config
    else
      echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config
    fi
    # 필요하면 다음도 해제: ChallengeResponseAuthentication no (주로 기본값이 no)
    if grep -qE '^[#\s]*ChallengeResponseAuthentication' /etc/ssh/sshd_config; then
      sed -i 's/^[#\s]*ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' /etc/ssh/sshd_config
    else
      echo 'ChallengeResponseAuthentication no' >> /etc/ssh/sshd_config
    fi

    # 2) SSH 서비스 재시작
    systemctl restart ssh || systemctl restart sshd || true

    # 3) (선택) 비번 만료 강제(최초 로그인 시 변경)
    passwd -e ubuntu || chage -d 0 ubuntu || true

    # 4) Nginx가 이미지에 이미 있을 때만 활성화 및 인덱스 복사
    if command -v nginx >/dev/null 2>&1; then
      systemctl enable --now nginx || service nginx start || true

      if [ -d /var/www/html ]; then
        cp -f /opt/vmcatalog/web-index.html /var/www/html/index.html
      elif [ -d /usr/share/nginx/html ]; then
        cp -f /opt/vmcatalog/web-index.html /usr/share/nginx/html/index.html
      else
        ROOT_DIR=$(awk '/root /{print $2}' /etc/nginx/nginx.conf /etc/nginx/conf.d/*.conf 2>/dev/null | head -n1 | tr -d ';')
        if [ -n "${ROOT_DIR:-}" ] && [ -d "$ROOT_DIR" ]; then
          cp -f /opt/vmcatalog/web-index.html "$ROOT_DIR/index.html"
        fi
      fi
    else
      echo "[vmcatalog] INFO: nginx not present (offline mode) - skipping" | tee -a /var/log/vmcatalog.log
    fi

timezone: Asia/Seoul
final_message: "Provisioned role=web (offline, password-login) on __HOSTNAME__"
